- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 # This is number
    COURSE: "DevSecOps with AWS" # is string
    IS_LIVE: true # boolean
    TOOLS: # list []
    - Linux
    - shell
    - Ansible
    CONCEPTS: # map or dictionary or object {}
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, is live?: {{ IS_LIVE }}, Tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}"    